### ISSUE TITLE
Download Not Working

### ISSUE THREAD

**Issue by Suleman-Elahi** [IsmaelHeredia/PasteBin_Manager#1]
The download option doesn't seem to be working !!!!

When I click the download button, nothing happens

**Comment by IsmaelHeredia** [comment]
The regular expression had changed in the page of pastebin, and i update this in the program, also I have to add a timeout between the downloads and some threads but that would be in another version.

Summary : Download error fixed

Greetings.

**Comment by Suleman-Elahi** [comment]
many thanks for this !!!
